drop extension if exists "pg_net";


  create table "public"."Folders" (
    "id" bigint generated by default as identity not null,
    "user_id" uuid not null default auth.uid(),
    "name" character varying not null default 'Untitled Folder'::character varying,
    "parent_id" bigint
      );


alter table "public"."Folders" enable row level security;

alter table "public"."Notes" add column "folder" bigint;

CREATE UNIQUE INDEX "Folders_pkey" ON public."Folders" USING btree (id);

alter table "public"."Folders" add constraint "Folders_pkey" PRIMARY KEY using index "Folders_pkey";

alter table "public"."Folders" add constraint "Folders_parent_id_fkey" FOREIGN KEY (parent_id) REFERENCES public."Folders"(id) ON DELETE CASCADE not valid;

alter table "public"."Folders" validate constraint "Folders_parent_id_fkey";

alter table "public"."Notes" add constraint "Notes_folder_fkey" FOREIGN KEY (folder) REFERENCES public."Folders"(id) ON DELETE CASCADE not valid;

alter table "public"."Notes" validate constraint "Notes_folder_fkey";

grant delete on table "public"."Folders" to "anon";

grant insert on table "public"."Folders" to "anon";

grant references on table "public"."Folders" to "anon";

grant select on table "public"."Folders" to "anon";

grant trigger on table "public"."Folders" to "anon";

grant truncate on table "public"."Folders" to "anon";

grant update on table "public"."Folders" to "anon";

grant delete on table "public"."Folders" to "authenticated";

grant insert on table "public"."Folders" to "authenticated";

grant references on table "public"."Folders" to "authenticated";

grant select on table "public"."Folders" to "authenticated";

grant trigger on table "public"."Folders" to "authenticated";

grant truncate on table "public"."Folders" to "authenticated";

grant update on table "public"."Folders" to "authenticated";

grant delete on table "public"."Folders" to "service_role";

grant insert on table "public"."Folders" to "service_role";

grant references on table "public"."Folders" to "service_role";

grant select on table "public"."Folders" to "service_role";

grant trigger on table "public"."Folders" to "service_role";

grant truncate on table "public"."Folders" to "service_role";

grant update on table "public"."Folders" to "service_role";


  create policy "Authenticated users can manage their own Folders"
  on "public"."Folders"
  as permissive
  for all
  to public
using (((auth.role() = 'authenticated'::text) AND (auth.uid() = user_id)))
with check (((auth.role() = 'authenticated'::text) AND (auth.uid() = user_id)));



